# Deploy database views to Snowflake via SnowSQL

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SF-Connect
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: '***SubscriptionResourceName***'
    KeyVaultName: '***ResourceName***'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: Bash@3
  env:
    SNOWSQL_DEST: ~/snowflake
    SNOWSQL_ACCOUNT: $(SF_ACCOUNT)
    SNOWSQL_USER: $(SnowUser)
    SNOWSQL_PWD: $(SnowPass)
  inputs:
    targetType: 'inline'
    script: |
      echo 'Starting bash task'
      echo 'Step 1: Installing SNOWSQL'
      
      curl -O https://sfc-repo.azure.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
      SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.21-linux_x86_64.bash
      
      echo 'Step 2: Creating  HHI view'
      ~/snowflake/snowsql -f HHI_NewExecutedLeases.sql -r rollName -w warehouseName 
      echo 'Step 3: Creating  Migration view'
      ~/snowflake/snowsql -f residentMigration.sql -r rollName -w warehouseName 
      echo 'Step 4: Creating  Delinquency view'
      ~/snowflake/snowsql -f Delinquency.sql -r rollName -w warehouseName 
      echo 'Step 5: Creating  LeaseTradeOutOrder view'
      ~/snowflake/snowsql -f tradeOutLeaseOrder.sql -r rollName -w warehouseName 
      echo 'Step 5: Creating  Rent Roll Base Report view'
      ~/snowflake/snowsql -f RentRollBaseReport.sql -r rollName -w warehouseName 
